# Generated by Django 4.2.5 on 2023-10-31 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='product',
            new_name='note',
        ),
    ]
