# Generated by Django 4.2.5 on 2023-10-31 16:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_rename_product_images_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
