# Generated by Django 4.2.5 on 2023-11-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_notes_filepdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
