# Generated by Django 4.2.5 on 2023-11-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_notes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
