# Generated by Django 4.2.5 on 2023-12-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_alter_category_slug_alter_notes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='status',
            field=models.CharField(choices=[('Evet', 'True'), ('Hayır', 'False')], max_length=10),
        ),
    ]
