# Generated by Django 4.2.5 on 2023-12-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_alter_notes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='status',
            field=models.CharField(choices=[('New', 'Yeni'), ('True', 'Evet'), ('False', 'Hayır')], max_length=10),
        ),
    ]
