# Generated by Django 4.2.5 on 2023-12-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_alter_notes_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='status',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır'), ('New', 'Yeni')], max_length=10),
        ),
    ]
