# Generated by Django 4.2.5 on 2023-10-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=60)),
                ('smtpserver', models.CharField(blank=True, max_length=30)),
                ('smtpemail', models.CharField(blank=True, max_length=30)),
                ('smtppassword', models.CharField(blank=True, max_length=30)),
                ('smtpport', models.CharField(blank=True, max_length=10)),
                ('icon', models.ImageField(blank=True, upload_to='images/')),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('youtube', models.CharField(blank=True, max_length=70)),
                ('linkedin', models.CharField(blank=True, max_length=90)),
                ('aboutus', models.TextField(blank=True)),
                ('contact', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayir')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
