# Generated by Django 4.2.5 on 2023-11-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='googleMap',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
