# Generated by Django 4.2.5 on 2023-12-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculumVitae', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ip', models.CharField(blank=True, max_length=25)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
