# Generated by Django 4.2.5 on 2023-12-20 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculumVitae', '0002_listmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamiCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('videourl', models.CharField(blank=True, max_length=255)),
                ('educationstatus', models.CharField(blank=True, max_length=255)),
                ('employmentstatus', models.CharField(blank=True, max_length=255)),
                ('birthdate', models.DateField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('workplace', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('startdate', models.DateField(blank=True)),
                ('enddate', models.DateField(blank=True)),
                ('order', models.IntegerField(blank=True)),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculumVitae.dynamicv')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=150)),
                ('unit', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('level', models.CharField(blank=True, max_length=150)),
                ('startdate', models.DateField(blank=True)),
                ('enddate', models.DateField(blank=True)),
                ('grade', models.CharField(blank=True, max_length=70)),
                ('order', models.IntegerField(blank=True)),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculumVitae.dynamicv')),
            ],
        ),
    ]
