# Generated by Django 4.2.5 on 2023-12-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculumVitae', '0003_dynamicv_experience_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicv',
            name='biolink',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
