# Generated by Django 4.2.5 on 2023-12-21 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculumVitae', '0005_dynamicv_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(blank=True, max_length=150)),
                ('skillgrade', models.IntegerField(blank=True)),
                ('certificate', models.CharField(blank=True, max_length=150)),
                ('certificateurl', models.CharField(blank=True, max_length=150)),
                ('certificatcode', models.CharField(blank=True, max_length=150)),
                ('certorg', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('startdate', models.DateField(blank=True)),
                ('enddate', models.DateField(blank=True)),
                ('order', models.IntegerField(blank=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculumVitae.dynamicv')),
            ],
        ),
    ]
