# Generated by Django 4.2.5 on 2023-12-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculumVitae', '0006_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='color',
            field=models.CharField(choices=[('primary', 'primary'), ('warning', 'warning'), ('danger', 'danger'), ('dark', 'dark'), ('info', 'info'), ('success', 'success')], default='primary', max_length=10),
        ),
    ]
