# Generated by Django 4.2.5 on 2023-12-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculumVitae', '0007_skill_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='certimage',
            field=models.ImageField(blank=True, upload_to='images/users/'),
        ),
    ]
