# Generated by Django 4.2.5 on 2023-11-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notecart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notecart',
            old_name='note',
            new_name='notes',
        ),
        migrations.AlterField(
            model_name='notecart',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
