# Generated by Django 4.2.5 on 2023-11-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notecart', '0002_rename_note_notecart_notes_alter_notecart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notecart',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
